services:
    - type: web
      name: CammionControlApp
      env: node
      plan: free
      rootDirectory: backend
      buildCommand: npm install && npm run build
      startCommand: npm start
      buildImage: "node:18"
      envVars:
          - key: NODE_ENV
            value: production
